[platformio]
build_dir = C:\Users\thaol\heriguard-build
build_cache_dir = C:\Users\thaol\heriguard-cache

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_deps = 
    matrix-robotics/MatrixMiniR4@^1.2.2
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.9
    arduino-libraries/ArduinoBLE@^1.3.6
